#!/bin/bash

set -e

ISO=$1
TARGET=$2
TMPDIR=/tmp

if [ ! -d $TARGET ];then
  echo "$TARGET is not a directory"
  exit
fi

if [ ! -f $ISO ];then
  echo "$ISO is not a file"
  exit
fi


DATAZIP=`pwd`/data.zip
if [ ! -f $DATAZIP ];then
  echo "Haftian boot data files are not found"
  exit
fi

MOUNTED_ISO=$TMPDIR/iso

mkdir -p $MOUNTED_ISO $TARGET
mount -o loop $ISO $MOUNTED_ISO

rsync -aL $MOUNTED_ISO/* $TARGET
cp -a $MOUNTED_ISO/.disk $TARGET

pushd $TARGET
unzip $DATAZIP
sed -i 's/set default=0 # Set the default menu entry/set default=0 # Set the default menu entry\ninsmod all_video/' boot/grub/grub.cfg
popd

umount $MOUNTED_ISO
umount $TARGET
rmdir $MOUNTED_ISO


